apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: Microservice
          image: pyrepo:default_python
          ports:
          - containerPort: 8008
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"